Better failure handling

diff --git a/.bin/esy b/.bin/esy
--- a/.bin/esy
+++ b/.bin/esy
@@ -26,10 +26,14 @@ SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 # Capturing stderr is very important to prevent nodejs from setting
 # stderr to nonblocking mode
 
-if [ "$1" == "build" ]; then
-  make -s -f <(/usr/bin/env node $SCRIPTDIR/esy.js build-eject $CURDIR 2>&1) build
-elif [ "$1" == "shell" ]; then
-  make -s -f <(/usr/bin/env node $SCRIPTDIR/esy.js build-eject $CURDIR 2>&1) shell
+if [ "$1" == "build" ] || [ "$1" == "shell" ]; then
+  MAKEFILE=`/usr/bin/env node $SCRIPTDIR/esy.js build-eject $CURDIR 2>&1`
+  if [ $? -ne 0 ]; then
+    echo "Failed to get dependency:"
+    printf "%s\n" "$MAKEFILE" >&2
+    exit 1
+  fi
+  make -s -f <(echo "$MAKEFILE") "$1"
 else
   SETENVCMD=$(/usr/bin/env node $SCRIPTDIR/esy.js "$@" $CURDIR 2>&1)
   if [ $? -ne 0 ]; then
